#!/usr/bin/bash

# edit

function mainf 
{
	sudo apt-get update -y
	
	# libraries 
	sudo apt-get install -y \
	make \
	cmake \
	git \
	gcc \
	g++ \
	python \
	python2 \
	python3 \
	default-jdk \
	libsdl2-dev \
	libsdl2-image-dev \
	libsdl2-mixer-dev \
	libsdl2-ttf-dev \
	libsdl2-gfx-dev \
	libsdl2-net-dev \
	freeglut3-dev

	# apllications
	sudo apt-get install -y \
	webcamoid \
	cheese \
	sublime-text \
	krita \
	blender \
	smplayer

	# apllications 2
	flatpak install -y \
	zoom \
	libresprite

	sudo apt-get upgrade

	# custom extra
	sudo apt-get install -y \
	python3-pip \
	xdotool \
	kdialog \
	feh


	echo "done"
}

# screenshot command: xfce4-screenshooter
# display img: feh --scale-down -g 500x500 fly.png

mainf