client_config_backend: settings
client_config:
  client_id: 841788210636-q4tragcgu5ull5119ohm6a6k9e2m6fo1.apps.googleusercontent.com
  client_secret: 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

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive.file
  - https://www.googleapis.com/auth/drive.install